# To set the application display name, only define either `app.name` or `app.name_byte_array`.
# For a rule of thumb:
# * Use `app.name` if your app name doesn't contain any non-ANSI characters.
# * Otherwise, convert your app name to UTF-8 byte array, comma delimited, and put
#   it in `app.name_byte_array`
#app.name=LÖVE for Android
# app.name_byte_array=76,195,150,86,69,32,102,111,114,32,65,110,100,114,111,105,100

app.name=Going Home: Revisited
app.activity_name=org.love2d.android.GameActivity
# app.activity_name=org.flamendless.admob.AdActivity
app.application_id=org.flamendless.goinghomerevisited
app.orientation=landscape
app.version_code=22
app.version_name=1.1.22

# Admob Extension configs
# flamendless.admob=0
admob.test_device_id=
admob.collect_consent=true
admob.privacy_url=https://flamendless.github.io/privacy/

# No need to modify anything past this line!
android.enableJetifier=false
android.useAndroidX=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# If you want faster building in the expense
# of background processses, set to true
org.gradle.daemon=false

# Use if you get out of memory exception
org.gradle.jvmargs=-Xmx4096m
